export interface DiagnosticAlertVars {
  client_name: string
  client_domain: string
  security_score: number | null
  seo_visibility: number | null
  revenue_leakage?: string
  booking_link?: string
  scan_date: string
}

export interface DossierVars {
  client_name: string
  client_domain: string
  onboarding_dossier_text: string
  booking_link?: string
}

export interface FollowUpVars {
  client_name: string
  client_domain: string
  security_score: number | null
  seo_visibility: number | null
  revenue_leakage?: string
  booking_link?: string
  day: 2 | 7
}

export interface CallBriefVars {
  client_name: string
  client_domain: string
  client_industry?: string
  security_score: number | null
  seo_visibility: number | null
  revenue_leakage?: string
  call_brief: string
  booking_link?: string
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function isHtml(text: string): boolean {
  return /<(p|ul|ol|li|strong|em|h[1-6]|br|div|span)[\s/>]/i.test(text)
}

// Applies dark-theme inline styles to HTML already generated by Gumloop
function applyDarkStyles(html: string): string {
  return html
    .replace(/<p>/gi,      '<p style="margin:0 0 16px;font-size:14px;color:#CBD5E1;line-height:1.75;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">')
    .replace(/<strong>/gi, '<strong style="color:#D4AF37;">')
    .replace(/<ul>/gi,     '<ul style="margin:0 0 16px;padding-left:20px;">')
    .replace(/<ol>/gi,     '<ol style="margin:0 0 16px;padding-left:20px;">')
    .replace(/<li>/gi,     '<li style="margin:0 0 8px;font-size:14px;color:#CBD5E1;line-height:1.6;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">')
    .replace(/&mdash;/gi,  '—')
}

// Converts call-brief markdown to styled HTML for email display
function renderBriefMarkdown(raw: string): string {
  const bold = (s: string) =>
    escapeHtml(s).replace(/\*\*(.+?)\*\*/g, '<strong style="color:#D4AF37;font-weight:700;">$1</strong>')

  const P  = 'margin:0 0 16px;font-size:14px;color:#CBD5E1;line-height:1.8;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;'
  const LI = 'margin:0 0 14px;font-size:14px;color:#CBD5E1;line-height:1.7;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;'
  const SI = 'margin:4px 0 10px;font-size:13px;color:#94A3B8;line-height:1.65;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;padding-left:10px;border-left:2px solid #334155;'
  const H2 = 'margin:22px 0 10px;font-size:11px;font-weight:700;color:#D4AF37;font-family:monospace;text-transform:uppercase;letter-spacing:0.14em;border-bottom:1px solid #1E293B;padding-bottom:6px;'

  const lines = raw.split('\n')
  const out: string[] = []
  let state: 'none' | 'ul' | 'ol' | 'sub' | 'para' = 'none'
  let paraAcc: string[] = []

  const closeAll = () => {
    if (state === 'ul' || state === 'sub') out.push('</ul>')
    if (state === 'ol')  out.push('</ol>')
    if (state === 'para' && paraAcc.length) {
      out.push(`<p style="${P}">${paraAcc.join('<br>')}</p>`)
      paraAcc = []
    }
    state = 'none'
  }

  for (const line of lines) {
    if (!line.trim()) { closeAll(); continue }

    if (line.startsWith('# ')) {
      closeAll()
      out.push(`<h2 style="${H2}">${bold(line.slice(2))}</h2>`)
      continue
    }
    if (line.startsWith('## ')) {
      closeAll()
      out.push(`<h3 style="margin:14px 0 8px;font-size:10px;font-weight:700;color:#64748B;font-family:monospace;text-transform:uppercase;letter-spacing:0.1em;">${bold(line.slice(3))}</h3>`)
      continue
    }
    if (/^ {2,}- /.test(line)) {
      const content = line.replace(/^ +-/, '').trim()
      if (state !== 'sub') { closeAll(); out.push('<ul style="margin:2px 0 14px;padding-left:0;list-style:none;">'); state = 'sub' }
      out.push(`<li style="${SI}">${bold(content)}</li>`)
      continue
    }
    if (line.startsWith('- ')) {
      if (state !== 'ul') { closeAll(); out.push('<ul style="margin:0 0 16px;padding-left:20px;">'); state = 'ul' }
      out.push(`<li style="${LI}">${bold(line.slice(2))}</li>`)
      continue
    }
    if (/^\d+\. /.test(line)) {
      if (state !== 'ol') { closeAll(); out.push('<ol style="margin:0 0 16px;padding-left:22px;">'); state = 'ol' }
      out.push(`<li style="${LI}">${bold(line.replace(/^\d+\. /, ''))}</li>`)
      continue
    }
    if (state !== 'para') { closeAll(); state = 'para' }
    paraAcc.push(bold(line))
  }
  closeAll()
  return out.join('\n')
}

// Branded header badge — shared by both email templates
function headerBadge(leftLabel: string): string {
  return `
<tr><td style="padding:24px 36px 0;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="border:1px solid #222;border-radius:6px;background:#0D0D0D;">
    <tr><td style="padding:14px 18px;">
      <p style="margin:0 0 10px;font-size:17px;font-family:monospace;font-weight:700;color:#FFFFFF;letter-spacing:0.2em;"><span style="color:#D4AF37;">369</span>&nbsp;AGENTIC SYSTEMS</p>
      <table width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
        <td><p style="margin:0;font-size:9px;font-family:monospace;color:#D4AF37;text-transform:uppercase;letter-spacing:0.12em;">&#9642;&nbsp;${leftLabel}</p></td>
        <td align="right"><p style="margin:0;font-size:9px;font-family:monospace;color:#475569;text-align:right;line-height:1.5;">SECURE TRANSMISSION<br>369-CORE v2.0</p></td>
      </tr></table>
    </td></tr>
  </table>
</td></tr>`
}

export function diagnosticAlertHtml(v: DiagnosticAlertVars): string {
  const sec  = v.security_score ?? '—'
  const seo  = v.seo_visibility ?? '—'
  const rev  = v.revenue_leakage ?? 'Calculating…'
  const book = v.booking_link ?? '#'
  const name = v.client_name || 'Business Owner'
  const dossierCode = `ALERT-${name.replace(/\s+/g, '_').toUpperCase()}`

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Diagnostic Alert — ${v.client_domain}</title>
</head>
<body style="margin:0;padding:0;background:#0A0A0A;">
<table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#0A0A0A;">
<tr><td align="center" style="padding:40px 16px;">
<table width="580" cellpadding="0" cellspacing="0" border="0" style="max-width:580px;width:100%;background:#0F0F0F;border:1px solid #1E1E1E;border-radius:8px;overflow:hidden;">

<tr><td height="3" style="background:#D4AF37;font-size:0;line-height:0;">&nbsp;</td></tr>

${headerBadge('AUTONOMOUS DIAGNOSTIC ALERT')}

<tr><td style="padding:24px 36px 20px;">
  <h1 style="margin:0 0 6px;font-size:22px;font-weight:700;color:#FFFFFF;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">System Scan Complete</h1>
  <p style="margin:0;font-size:12px;font-family:monospace;color:#475569;">${v.client_domain} &nbsp;·&nbsp; ${v.scan_date}</p>
</td></tr>

<tr><td style="padding:0 36px 24px;">
  <p style="margin:0;font-size:14px;color:#94A3B8;line-height:1.75;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">Hi ${name},<br><br>Our autonomous intelligence system has completed a full-spectrum audit of your digital infrastructure. The readings below represent live operational data captured from your environment.</p>
</td></tr>

<tr><td style="padding:0 36px 28px;">
<table width="100%" cellpadding="0" cellspacing="0" border="0"><tr>

  <td style="width:31%;background:#141414;border:1px solid #222;border-top:2px solid #EF4444;border-radius:6px;padding:16px 10px;text-align:center;vertical-align:top;">
    <p style="margin:0 0 8px;font-size:9px;font-family:monospace;color:#94A3B8;text-transform:uppercase;letter-spacing:0.12em;">Security</p>
    <p style="margin:0;font-size:30px;font-weight:700;color:#FFFFFF;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;line-height:1;">${sec}</p>
    <p style="margin:6px 0 0;font-size:9px;font-family:monospace;color:#EF4444;">/100</p>
  </td>

  <td width="3%">&nbsp;</td>

  <td style="width:31%;background:#141414;border:1px solid #222;border-top:2px solid #D4AF37;border-radius:6px;padding:16px 10px;text-align:center;vertical-align:top;">
    <p style="margin:0 0 8px;font-size:9px;font-family:monospace;color:#94A3B8;text-transform:uppercase;letter-spacing:0.12em;">SEO Visibility</p>
    <p style="margin:0;font-size:30px;font-weight:700;color:#FFFFFF;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;line-height:1;">${seo}</p>
    <p style="margin:6px 0 0;font-size:9px;font-family:monospace;color:#D4AF37;">/100</p>
  </td>

  <td width="3%">&nbsp;</td>

  <td style="width:31%;background:#141414;border:1px solid #222;border-top:2px solid #D4AF37;border-radius:6px;padding:16px 10px;text-align:center;vertical-align:top;">
    <p style="margin:0 0 8px;font-size:9px;font-family:monospace;color:#94A3B8;text-transform:uppercase;letter-spacing:0.12em;">Revenue Leak</p>
    <p style="margin:0;font-size:24px;font-weight:700;color:#D4AF37;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;line-height:1;">${rev}</p>
    <p style="margin:6px 0 0;font-size:9px;font-family:monospace;color:#D4AF37;">/mo est.</p>
  </td>

</tr></table>
</td></tr>

<tr><td style="padding:0 36px 24px;">
  <table width="100%" cellpadding="0" cellspacing="0"><tr><td height="1" style="background:#1E1E1E;font-size:0;line-height:0;">&nbsp;</td></tr></table>
</td></tr>

<tr><td style="padding:0 36px 28px;">
  <p style="margin:0 0 14px;font-size:14px;color:#CBD5E1;line-height:1.75;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">These vulnerabilities are currently active in your environment. Our autonomous patch system can seal the security gap, recover estimated revenue leakage, and boost your search presence — all without disrupting your operations.</p>
  <p style="margin:0;font-size:14px;color:#CBD5E1;line-height:1.75;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">A full operational dossier for <strong style="color:#FFFFFF;">${v.client_domain}</strong> is landing in your inbox shortly. In the meantime, book a direct call with a specialist:</p>
</td></tr>

<tr><td style="padding:0 36px 36px;text-align:center;">
  <!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" href="${book}" style="height:50px;v-text-anchor:middle;width:300px;" arcsize="4%" stroke="f" fillcolor="#D4AF37"><w:anchorlock/><center style="color:#080808;font-family:sans-serif;font-size:12px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;">SCHEDULE DIAGNOSTIC CALL →</center></v:roundrect><![endif]-->
  <!--[if !mso]><!-->
  <a href="${book}" style="display:inline-block;background:#D4AF37;color:#080808;font-family:monospace;font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;text-decoration:none;padding:15px 32px;border-radius:4px;">SCHEDULE DIAGNOSTIC CALL →</a>
  <!--<![endif]-->
</td></tr>

<tr><td style="padding:16px 36px;border-top:1px solid #1A1A1A;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
    <td>
      <p style="margin:0;font-size:10px;font-family:monospace;color:#334155;">369 Agentic Systems &middot; AI Workforce Infrastructure</p>
      <p style="margin:4px 0 0;font-size:10px;font-family:monospace;"><a href="mailto:intelligence@369agenticsystems.com" style="color:#475569;text-decoration:none;">intelligence@369agenticsystems.com</a></p>
    </td>
    <td align="right" style="vertical-align:top;">
      <p style="margin:0;font-size:9px;font-family:monospace;color:#1E293B;text-align:right;line-height:1.6;">${escapeHtml(dossierCode)}<br>369-CORE ENCRYPTED</p>
    </td>
  </tr></table>
</td></tr>

</table>
</td></tr>
</table>
</body>
</html>`
}

export function callBriefHtml(v: CallBriefVars): string {
  const name      = v.client_name || 'Business Owner'
  const firstName = name.split(' ')[0]
  const book      = v.booking_link ?? 'https://cal.com/369agentic/30min'
  const sec       = v.security_score ?? '—'
  const seo       = v.seo_visibility ?? '—'
  const rev       = v.revenue_leakage ?? 'Calculating…'
  const industry  = v.client_industry ?? 'Business'

  const rawBrief = typeof v.call_brief === 'string' ? v.call_brief : String(v.call_brief || '')

  const briefHtml = isHtml(rawBrief) ? applyDarkStyles(rawBrief) : renderBriefMarkdown(rawBrief)

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Call Brief — ${v.client_domain}</title>
</head>
<body style="margin:0;padding:0;background:#0A0A0A;">
<table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#0A0A0A;">
<tr><td align="center" style="padding:40px 16px;">
<table width="600" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;background:#0F0F0F;border:1px solid #1E1E1E;border-radius:8px;overflow:hidden;">

<tr><td height="3" style="background:#F59E0B;font-size:0;line-height:0;">&nbsp;</td></tr>

${headerBadge('CALL BRIEF — INTERNAL USE ONLY')}

<!-- Header -->
<tr><td style="padding:24px 36px 8px;">
  <h1 style="margin:0 0 4px;font-size:20px;font-weight:700;color:#FFFFFF;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">Pre-Call Intelligence File</h1>
  <p style="margin:0;font-size:12px;font-family:monospace;color:#475569;">${v.client_domain} &nbsp;·&nbsp; ${escapeHtml(industry)}</p>
</td></tr>

<!-- Prospect snapshot -->
<tr><td style="padding:16px 36px 24px;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#111111;border:1px solid #1E1E1E;border-radius:8px;">
    <tr><td style="padding:16px 18px;">
      <p style="margin:0 0 10px;font-size:9px;font-family:monospace;color:#F59E0B;text-transform:uppercase;letter-spacing:0.15em;">&#9642;&nbsp;PROSPECT</p>
      <p style="margin:0 0 2px;font-size:16px;font-weight:700;color:#FFFFFF;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">${escapeHtml(name)}</p>
      <p style="margin:0;font-size:12px;font-family:monospace;color:#475569;">${v.client_domain} &nbsp;·&nbsp; ${escapeHtml(industry)}</p>
    </td></tr>
  </table>
</td></tr>

<!-- Metric chips -->
<tr><td style="padding:0 36px 24px;">
<table width="100%" cellpadding="0" cellspacing="0" border="0"><tr>

  <td style="width:31%;background:#141414;border:1px solid #222;border-top:2px solid #EF4444;border-radius:6px;padding:14px 10px;text-align:center;vertical-align:top;">
    <p style="margin:0 0 6px;font-size:9px;font-family:monospace;color:#94A3B8;text-transform:uppercase;letter-spacing:0.12em;">Security</p>
    <p style="margin:0;font-size:26px;font-weight:700;color:#FFFFFF;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;line-height:1;">${sec}</p>
    <p style="margin:4px 0 0;font-size:9px;font-family:monospace;color:#EF4444;">/100</p>
  </td>

  <td width="3%">&nbsp;</td>

  <td style="width:31%;background:#141414;border:1px solid #222;border-top:2px solid #D4AF37;border-radius:6px;padding:14px 10px;text-align:center;vertical-align:top;">
    <p style="margin:0 0 6px;font-size:9px;font-family:monospace;color:#94A3B8;text-transform:uppercase;letter-spacing:0.12em;">SEO Vis.</p>
    <p style="margin:0;font-size:26px;font-weight:700;color:#FFFFFF;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;line-height:1;">${seo}</p>
    <p style="margin:4px 0 0;font-size:9px;font-family:monospace;color:#D4AF37;">/100</p>
  </td>

  <td width="3%">&nbsp;</td>

  <td style="width:31%;background:#141414;border:1px solid #222;border-top:2px solid #D4AF37;border-radius:6px;padding:14px 10px;text-align:center;vertical-align:top;">
    <p style="margin:0 0 6px;font-size:9px;font-family:monospace;color:#94A3B8;text-transform:uppercase;letter-spacing:0.12em;">Rev. Leak</p>
    <p style="margin:0;font-size:20px;font-weight:700;color:#D4AF37;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;line-height:1;">${rev}</p>
    <p style="margin:4px 0 0;font-size:9px;font-family:monospace;color:#D4AF37;">/mo est.</p>
  </td>

</tr></table>
</td></tr>

<!-- Divider -->
<tr><td style="padding:0 36px 24px;">
  <table width="100%" cellpadding="0" cellspacing="0"><tr><td height="1" style="background:#1E1E1E;font-size:0;line-height:0;">&nbsp;</td></tr></table>
</td></tr>

<!-- Call brief section label -->
<tr><td style="padding:0 36px 12px;">
  <span style="display:inline-block;padding:5px 12px;border:1px solid rgba(245,158,11,0.25);border-left:3px solid #F59E0B;background:rgba(245,158,11,0.06);font-size:9px;font-family:monospace;color:#F59E0B;text-transform:uppercase;letter-spacing:0.15em;">CALL SCRIPT &amp; TALKING POINTS</span>
</td></tr>
<tr><td style="padding:0 36px 16px;">
  <h2 style="margin:0;font-size:18px;font-weight:700;color:#FFFFFF;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">Your 30-Minute Brief for ${escapeHtml(firstName)}</h2>
</td></tr>

<!-- Brief content box -->
<tr><td style="padding:0 36px 28px;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#111111;border:1px solid #1E1E1E;border-radius:8px;">
    <tr><td style="padding:24px 22px;">
${briefHtml}
    </td></tr>
  </table>
</td></tr>

<!-- Cal link reminder -->
<tr><td style="padding:0 36px 36px;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:rgba(245,158,11,0.04);border:1px solid rgba(245,158,11,0.18);border-radius:8px;">
    <tr><td style="padding:18px 24px;text-align:center;">
      <p style="margin:0 0 4px;font-size:9px;font-family:monospace;color:#F59E0B;text-transform:uppercase;letter-spacing:0.2em;">PROSPECT BOOKING LINK</p>
      <a href="${book}" style="font-size:11px;font-family:monospace;color:#D4AF37;text-decoration:underline;">${book}</a>
    </td></tr>
  </table>
</td></tr>

<!-- Footer -->
<tr><td style="padding:16px 36px;border-top:1px solid #1A1A1A;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
    <td><p style="margin:0;font-size:10px;font-family:monospace;color:#334155;">369 Agentic Systems &middot; Internal Command Center</p></td>
    <td align="right"><p style="margin:0;font-size:9px;font-family:monospace;color:#1E293B;text-align:right;line-height:1.6;">BRIEF-${escapeHtml(name.replace(/\s+/g, '_').toUpperCase())}<br>EYES ONLY</p></td>
  </tr></table>
</td></tr>

</table>
</td></tr>
</table>
</body>
</html>`
}

export function followUpHtml(v: FollowUpVars): string {
  const name      = v.client_name || 'Business Owner'
  const firstName = name.split(' ')[0]
  const book      = v.booking_link ?? 'https://cal.com/369agentic/30min'
  const sec       = v.security_score ?? '—'
  const seo       = v.seo_visibility ?? '—'
  const rev       = v.revenue_leakage ?? 'an estimated amount'

  const isDay7 = v.day === 7
  const subjectLabel = isDay7 ? 'FINAL FOLLOW-UP' : 'DAY-2 CHECK-IN'
  const accentColor  = isDay7 ? '#EF4444' : '#D4AF37'

  const bodyContent = isDay7
    ? `<p style="margin:0 0 16px;font-size:15px;color:#CBD5E1;line-height:1.8;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">Hi ${escapeHtml(firstName)},</p>
      <p style="margin:0 0 16px;font-size:14px;color:#94A3B8;line-height:1.8;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">We're closing out your audit file for <strong style="color:#FFFFFF;">${v.client_domain}</strong>. Our scan flagged a security score of <strong style="color:#EF4444;">${sec}/100</strong> and an estimated revenue leak of <strong style="color:#EF4444;">${rev}/mo</strong> — that gap stays open until someone closes it.</p>
      <p style="margin:0 0 24px;font-size:14px;color:#94A3B8;line-height:1.8;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">If the timing isn't right, no problem. When it is, we're ready to deploy. If you have questions, reply to this email directly — I read every one.</p>`
    : `<p style="margin:0 0 16px;font-size:15px;color:#CBD5E1;line-height:1.8;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">Hi ${escapeHtml(firstName)},</p>
      <p style="margin:0 0 16px;font-size:14px;color:#94A3B8;line-height:1.8;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">We sent your diagnostic results for <strong style="color:#FFFFFF;">${v.client_domain}</strong> 48 hours ago and wanted to make sure everything landed. Your scan came back with a security score of <strong style="color:#D4AF37;">${sec}/100</strong>, an SEO visibility of <strong style="color:#D4AF37;">${seo}/100</strong>, and an estimated revenue leak of <strong style="color:#D4AF37;">${rev}/mo</strong>.</p>
      <p style="margin:0 0 24px;font-size:14px;color:#94A3B8;line-height:1.8;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">If you have questions about the numbers or want to walk through the dossier together, book a 30-minute call — we can review everything live and show you exactly how the Digital Employee would close those gaps.</p>`

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${isDay7 ? 'Final Follow-Up' : 'Day-2 Check-In'} — ${v.client_domain}</title>
</head>
<body style="margin:0;padding:0;background:#0A0A0A;">
<table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#0A0A0A;">
<tr><td align="center" style="padding:40px 16px;">
<table width="560" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;width:100%;background:#0F0F0F;border:1px solid #1E1E1E;border-radius:8px;overflow:hidden;">

<tr><td height="3" style="background:${accentColor};font-size:0;line-height:0;">&nbsp;</td></tr>

${headerBadge(subjectLabel)}

<tr><td style="padding:28px 36px 12px;">
  <h1 style="margin:0 0 4px;font-size:18px;font-weight:700;color:#FFFFFF;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">${isDay7 ? 'One Last Note' : 'Checking In'}</h1>
  <p style="margin:0;font-size:11px;font-family:monospace;color:#475569;">${v.client_domain}</p>
</td></tr>

<tr><td style="padding:12px 36px 28px;">
${bodyContent}
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="text-align:center;">
    <tr><td>
      <a href="${book}" style="display:inline-block;background:${accentColor};color:#080808;font-family:monospace;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;text-decoration:none;padding:14px 28px;border-radius:4px;">${isDay7 ? 'BOOK A CALL BEFORE WE CLOSE YOUR FILE →' : 'BOOK YOUR 30-MINUTE CALL →'}</a>
    </td></tr>
  </table>
</td></tr>

<tr><td style="padding:16px 36px;border-top:1px solid #1A1A1A;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
    <td><p style="margin:0;font-size:10px;font-family:monospace;color:#334155;">369 Agentic Systems &middot; AI Workforce Infrastructure</p></td>
  </tr></table>
</td></tr>

</table>
</td></tr>
</table>
</body>
</html>`
}

export function dossierHtml(v: DossierVars): string {
  const name      = v.client_name || 'Business Owner'
  const firstName = name.split(' ')[0]
  const book      = v.booking_link ?? '#'
  const dossierCode = `DOSSIER-${name.replace(/\s+/g, '_').toUpperCase()}`

  // Normalize input to string regardless of what Gumloop sends
  const rawText = typeof v.onboarding_dossier_text === 'string'
    ? v.onboarding_dossier_text
    : typeof v.onboarding_dossier_text === 'object' && v.onboarding_dossier_text !== null
      ? JSON.stringify(v.onboarding_dossier_text, null, 2)
      : String(v.onboarding_dossier_text || '')

  // If Gumloop sends pre-built HTML, apply dark theme styles directly.
  // If it sends plain text, convert paragraphs and markdown headers to HTML.
  const bodyHtml = isHtml(rawText)
    ? applyDarkStyles(rawText)
    : rawText
        .split(/\n{2,}/)
        .map(para => para.trim())
        .filter(Boolean)
        .map(para => {
          if (para.startsWith('# ')) {
            return `<h2 style="margin:0 0 10px;font-size:15px;font-weight:700;color:#D4AF37;font-family:monospace;text-transform:uppercase;letter-spacing:0.08em;">${escapeHtml(para.slice(2))}</h2>`
          }
          if (para.startsWith('## ')) {
            return `<h3 style="margin:0 0 8px;font-size:12px;font-weight:700;color:#94A3B8;font-family:monospace;text-transform:uppercase;letter-spacing:0.06em;">${escapeHtml(para.slice(3))}</h3>`
          }
          return `<p style="margin:0 0 16px;font-size:14px;color:#CBD5E1;line-height:1.75;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">${escapeHtml(para).replace(/\n/g, '<br>')}</p>`
        })
        .join('\n')

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Operations Dossier — ${v.client_domain}</title>
</head>
<body style="margin:0;padding:0;background:#0A0A0A;">
<table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#0A0A0A;">
<tr><td align="center" style="padding:40px 16px;">
<table width="600" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;background:#0F0F0F;border:1px solid #1E1E1E;border-radius:8px;overflow:hidden;">

<tr><td height="3" style="background:#D4AF37;font-size:0;line-height:0;">&nbsp;</td></tr>

${headerBadge('ONBOARDING DOSSIER — CONFIDENTIAL')}

<!-- Hero intro -->
<tr><td style="padding:28px 36px 20px;">
  <h1 style="margin:0 0 12px;font-size:26px;font-weight:700;color:#FFFFFF;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">Hello, ${escapeHtml(firstName)}.</h1>
  <p style="margin:0;font-size:14px;color:#94A3B8;line-height:1.75;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">Your Digital Employee has completed its initial intelligence pass. Below is your personalized Onboarding Dossier — a full operational brief prepared exclusively for <strong style="color:#FFFFFF;">${v.client_domain}</strong> by the 369 Agentic Core.</p>
</td></tr>

<!-- Divider -->
<tr><td style="padding:0 36px 24px;">
  <table width="100%" cellpadding="0" cellspacing="0"><tr><td height="1" style="background:#1E1E1E;font-size:0;line-height:0;">&nbsp;</td></tr></table>
</td></tr>

<!-- Section 01 label -->
<tr><td style="padding:0 36px 12px;">
  <span style="display:inline-block;padding:5px 12px;border:1px solid rgba(212,175,55,0.25);border-left:3px solid #D4AF37;background:rgba(212,175,55,0.06);font-size:9px;font-family:monospace;color:#D4AF37;text-transform:uppercase;letter-spacing:0.15em;">SECTION 01 &mdash; OPERATIONAL AUDIT</span>
</td></tr>
<tr><td style="padding:0 36px 16px;">
  <h2 style="margin:0;font-size:20px;font-weight:700;color:#FFFFFF;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">Your Business Intelligence Report</h2>
</td></tr>

<!-- Content box -->
<tr><td style="padding:0 36px 28px;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#111111;border:1px solid #1E1E1E;border-radius:8px;">
    <tr><td style="padding:24px 22px;">
${bodyHtml}
    </td></tr>
  </table>
</td></tr>

<!-- Mid CTA banner -->
<tr><td style="padding:0 36px 28px;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:rgba(212,175,55,0.04);border:1px solid rgba(212,175,55,0.18);border-radius:8px;">
    <tr><td style="padding:22px 24px;text-align:center;">
      <p style="margin:0 0 14px;font-size:9px;font-family:monospace;color:#D4AF37;text-transform:uppercase;letter-spacing:0.2em;">YOUR DIGITAL EMPLOYEES ARE STANDING BY</p>
      <!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" href="${book}" style="height:44px;v-text-anchor:middle;width:280px;" arcsize="4%" stroke="f" fillcolor="#D4AF37"><w:anchorlock/><center style="color:#080808;font-family:sans-serif;font-size:11px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;">DEPLOY YOUR SPECIALIST NOW →</center></v:roundrect><![endif]-->
      <!--[if !mso]><!-->
      <a href="${book}" style="display:inline-block;background:#D4AF37;color:#080808;font-family:monospace;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;text-decoration:none;padding:13px 28px;border-radius:4px;">DEPLOY YOUR SPECIALIST NOW &rarr;</a>
      <!--<![endif]-->
    </td></tr>
  </table>
</td></tr>

<!-- Next step box -->
<tr><td style="padding:0 36px 36px;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#111111;border:1px solid #1E1E1E;border-radius:8px;">
    <tr><td style="padding:28px 24px;text-align:center;">
      <p style="margin:0 0 10px;font-size:9px;font-family:monospace;color:#D4AF37;text-transform:uppercase;letter-spacing:0.2em;">NEXT STEP</p>
      <h3 style="margin:0 0 12px;font-size:20px;font-weight:700;color:#FFFFFF;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">Ready to Deploy Your Digital Employee?</h3>
      <p style="margin:0 0 20px;font-size:13px;color:#94A3B8;line-height:1.6;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;">Schedule your 30-minute strategy call. We will review this dossier together and configure your workforce for launch.</p>
      <!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" href="${book}" style="height:50px;v-text-anchor:middle;width:300px;" arcsize="4%" stroke="f" fillcolor="#D4AF37"><w:anchorlock/><center style="color:#080808;font-family:sans-serif;font-size:12px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;">BOOK YOUR STRATEGY CALL →</center></v:roundrect><![endif]-->
      <!--[if !mso]><!-->
      <a href="${book}" style="display:inline-block;background:#D4AF37;color:#080808;font-family:monospace;font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;text-decoration:none;padding:15px 32px;border-radius:4px;">BOOK YOUR STRATEGY CALL &rarr;</a>
      <!--<![endif]-->
    </td></tr>
  </table>
</td></tr>

<!-- Footer -->
<tr><td style="padding:16px 36px;border-top:1px solid #1A1A1A;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
    <td>
      <p style="margin:0;font-size:10px;font-family:monospace;color:#334155;">369 Agentic Systems &middot; AI Workforce Infrastructure</p>
      <p style="margin:4px 0 0;font-size:10px;font-family:monospace;"><a href="mailto:intelligence@369agenticsystems.com" style="color:#475569;text-decoration:none;">intelligence@369agenticsystems.com</a></p>
    </td>
    <td align="right" style="vertical-align:top;">
      <p style="margin:0;font-size:9px;font-family:monospace;color:#1E293B;text-align:right;line-height:1.6;">${escapeHtml(dossierCode)}<br>369-CORE ENCRYPTED</p>
    </td>
  </tr></table>
  <p style="margin:10px 0 0;font-size:10px;font-family:monospace;color:#1E293B;line-height:1.5;">This dossier was compiled by your dedicated Digital Employee and contains proprietary analysis prepared exclusively for ${escapeHtml(name)}. If you received this in error, please disregard. To unsubscribe, <a href="#" style="color:#334155;">click here</a>.</p>
</td></tr>

</table>
</td></tr>
</table>
</body>
</html>`
}
